apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: build-notif
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/s9-demo/build-notif:latest
            env:
            - name: RELEASE
              value: "v0.1.10"
            - name: NOTIFS_FOR_APP
              value: "maxprime" # name of the app to send notifications for
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: build-notif-secrets
                  key: SLACK_API_TOKEN
            - name: SLACK_BUILD_STATUS_CHANNEL
              value: CGUKV76EA #channel ID, not the name

