apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: slacker-dumper
spec:
  # filter:
  #   sourceAndType:
  #     type: com.twitter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: build-notif